// This file will be generated by: npx supabase gen types typescript --project-id <id> > src/types/database.ts
// For now, we'll use manually defined types based on our schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      tasks: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          state:
            | "backlog"
            | "planned"
            | "in_progress"
            | "blocked"
            | "paused"
            | "done"
            | "dropped";
          category:
            | "class"
            | "recruiting"
            | "team_research"
            | "personal"
            | null;
          task_type:
            | "coding"
            | "study_reading"
            | "writing_report"
            | "admin_logistics"
            | "interview_prep"
            | null;
          hard_deadline: boolean;
          estimated_minutes: number | null;
          priority_label: "low" | "medium" | "high" | "critical" | null;
          importance: "low" | "medium" | "high" | "critical" | null;
          difficulty: "easy" | "medium" | "hard" | "extreme" | null;
          due_at: string | null;
          planned_start_at: string | null;
          planned_end_at: string | null;
          completed_at: string | null;
          course_id: string | null;
          log_date: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          description?: string | null;
          state?:
            | "backlog"
            | "planned"
            | "in_progress"
            | "blocked"
            | "paused"
            | "done"
            | "dropped";
          category?:
            | "class"
            | "recruiting"
            | "team_research"
            | "personal"
            | null;
          task_type?:
            | "coding"
            | "study_reading"
            | "writing_report"
            | "admin_logistics"
            | "interview_prep"
            | null;
          hard_deadline?: boolean;
          estimated_minutes?: number | null;
          priority_label?: "low" | "medium" | "high" | "critical" | null;
          importance?: "low" | "medium" | "high" | "critical" | null;
          difficulty?: "easy" | "medium" | "hard" | "extreme" | null;
          due_at?: string | null;
          planned_start_at?: string | null;
          planned_end_at?: string | null;
          completed_at?: string | null;
          course_id?: string | null;
          log_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string | null;
          state?:
            | "backlog"
            | "planned"
            | "in_progress"
            | "blocked"
            | "paused"
            | "done"
            | "dropped";
          category?:
            | "class"
            | "recruiting"
            | "team_research"
            | "personal"
            | null;
          task_type?:
            | "coding"
            | "study_reading"
            | "writing_report"
            | "admin_logistics"
            | "interview_prep"
            | null;
          hard_deadline?: boolean;
          estimated_minutes?: number | null;
          priority_label?: "low" | "medium" | "high" | "critical" | null;
          importance?: "low" | "medium" | "high" | "critical" | null;
          difficulty?: "easy" | "medium" | "hard" | "extreme" | null;
          due_at?: string | null;
          planned_start_at?: string | null;
          planned_end_at?: string | null;
          completed_at?: string | null;
          course_id?: string | null;
          log_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "tasks_course_id_fkey";
            columns: ["course_id"];
            referencedRelation: "courses";
            referencedColumns: ["id"];
          },
        ];
      };
      task_events: {
        Row: {
          id: string;
          task_id: string;
          event_type: string;
          payload: Json | null;
          old_state: string | null;
          new_state: string | null;
          old_due_at: string | null;
          new_due_at: string | null;
          old_planned_start_at: string | null;
          new_planned_start_at: string | null;
          old_planned_end_at: string | null;
          new_planned_end_at: string | null;
          changes_summary: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          task_id: string;
          event_type: string;
          payload?: Json | null;
          old_state?: string | null;
          new_state?: string | null;
          old_due_at?: string | null;
          new_due_at?: string | null;
          old_planned_start_at?: string | null;
          new_planned_start_at?: string | null;
          old_planned_end_at?: string | null;
          new_planned_end_at?: string | null;
          changes_summary?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          task_id?: string;
          event_type?: string;
          payload?: Json | null;
          old_state?: string | null;
          new_state?: string | null;
          old_due_at?: string | null;
          new_due_at?: string | null;
          old_planned_start_at?: string | null;
          new_planned_start_at?: string | null;
          old_planned_end_at?: string | null;
          new_planned_end_at?: string | null;
          changes_summary?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "task_events_task_id_fkey";
            columns: ["task_id"];
            referencedRelation: "tasks";
            referencedColumns: ["id"];
          },
        ];
      };
      courses: {
        Row: {
          id: string;
          name: string;
          days: string[] | null;
          start_time_str: string | null;
          end_time_str: string | null;
          day_schedules: Json | null;
          semester: string | null;
          credits: number | null;
          is_virtual: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          days?: string[] | null;
          start_time_str?: string | null;
          end_time_str?: string | null;
          day_schedules?: Json | null;
          semester?: string | null;
          credits?: number | null;
          is_virtual?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          days?: string[] | null;
          start_time_str?: string | null;
          end_time_str?: string | null;
          day_schedules?: Json | null;
          semester?: string | null;
          credits?: number | null;
          is_virtual?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      daily_logs: {
        Row: {
          id: string;
          date: string;
          energy: number | null;
          focus: number | null;
          stress: number | null;
          sleep_hours: number | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          date: string;
          energy?: number | null;
          focus?: number | null;
          stress?: number | null;
          sleep_hours?: number | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          date?: string;
          energy?: number | null;
          focus?: number | null;
          stress?: number | null;
          sleep_hours?: number | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      tasks_enriched: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          state:
            | "backlog"
            | "planned"
            | "in_progress"
            | "blocked"
            | "paused"
            | "done"
            | "dropped";
          category:
            | "class"
            | "recruiting"
            | "team_research"
            | "personal"
            | null;
          task_type:
            | "coding"
            | "study_reading"
            | "writing_report"
            | "admin_logistics"
            | "interview_prep"
            | null;
          hard_deadline: boolean;
          estimated_minutes: number | null;
          priority_label: "low" | "medium" | "high" | "critical" | null;
          importance: "low" | "medium" | "high" | "critical" | null;
          difficulty: "easy" | "medium" | "hard" | "extreme" | null;
          due_at: string | null;
          planned_start_at: string | null;
          planned_end_at: string | null;
          completed_at: string | null;
          course_id: string | null;
          log_date: string | null;
          created_at: string;
          updated_at: string;
          planned_minutes: number;
          days_until_due: number | null;
          is_overdue: boolean;
          cycle_time_hours: number | null;
          lateness_hours: number | null;
          on_time: boolean;
          risk_score: number;
        };
        Relationships: [
          {
            foreignKeyName: "tasks_course_id_fkey";
            columns: ["course_id"];
            referencedRelation: "courses";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}
